export const APP_CONSTANTS = {
  DEFAULT_CURRENCY: "INR",
  CURRENCY_SYMBOL: "₹",
  ITEMS_PER_PAGE: 8,
  MAX_CART_QUANTITY: 10,
  MIN_CART_QUANTITY: 1,
  SEARCH_DEBOUNCE_DELAY: 400,
  TOAST_DURATION: 3000,
  DEFAULT_PRODUCT_RATING: 5,
};